### ISSUE TITLE
Github not integrated but asking for a token and failed afterwards.

### ISSUE THREAD

**Issue by sasi-uvr** [CircleCI-Public/CircleCI-Env-Inspector#11]
Once I run the "run.sh", prompt for Circle-Ci token is shown, then Github token. I don't have Github integration with Circle-ci. With or without supplying the Github token, it shows my org info and asks to confirm the Org. Then it fails saying "bad credentials". If it is a bad credentials, how is it getting my Org info?

**Comment by KyleTryon** [comment]
Hey @sasi-uvr 
This tool assumed the repositories connected to your account are GitHub VCS repos. We plan to add BitBucket today. Can you confirm, are you a BitBucket user?

The list of organizations comes from CircleCI. The list of repos connected to it, at least for GitHub, we are using a GitHub API call to take advantage of fewer API calls to GitHub in total, which is meant to reduce rate limiting.
