### ISSUE TITLE
Feature Request: Ability to audit environment/context usage

### ISSUE THREAD

**Issue by BenCoffeed** [CircleCI-Public/CircleCI-Env-Inspector#16]
I have a large number of repositories and have several stale contexts from old projects that were not named well by predecessors. It would be very useful to have some . . . context. . . when troubleshooting contexts. ie What project(s) user(s) read a particular value most recently?

**Comment by BenCoffeed** [comment]
Also, having the ability to dive into further usage for a particular variable would be nice as well. . . perhaps only show the most recent result unless additional verbosity was requested, or even have a more granular tool that supports specific context/environment/variable reports which could give a full history.

**Comment by KyleTryon** [comment]
Hello Ben,

Thank you for the suggestion. Unfortunately, that is not information that is returned by the API, and thus not something that could be included in this tool. For detailed audit information, please contact CircleCI support with the request for the data you would like to be obtained.
