### ISSUE TITLE
Additional tool / possible collab

### ISSUE THREAD

**Issue by blimmer** [CircleCI-Public/CircleCI-Env-Inspector#17]
I didn't realize that this existed, so I started `circleci-audit` today. It uses `oclif` and is MIT licensed, in case you want to contribute / extend it instead of, or in addition to this tool: https://github.com/blimmer/circleci-audit/

**Comment by KyleTryon** [comment]
Hey @blimmer thanks for sharing this! I hadn't gotten a chance to look at your post right away in the mad dash of things. It looks great and I love the tabular output. We have been discussing what if anything to change about ours. Currently, we just return JSON but I think that may be the most versatile to work with.

Anyway, long rant to say love the project and are happy to collaborate in any way we can. Thank you for building this and helping people so quickly.

**Comment by KyleTryon** [comment]
Hey @blimmer thanks again. Things on this project have finally slowed down with the release of V2. We will now be doing less extensive changes now that the code is in its V2 state, and we can more easily accept PRs and feature requests.

We'd love your feedback and any ideas for changes.
