### ISSUE TITLE
Feature request: automatically run against all organizations in one run

### ISSUE THREAD

**Issue by alexkli** [CircleCI-Public/CircleCI-Env-Inspector#18]
Problem: Currently one has to run the script multiple times for each organization/user one has access to. In order to get all the contexts IIUC (the project list seems always the same). Each time it overwrites the previous `circleci-data.json` file if one isn't careful.

Request: It could just automatically iterate over all orgs and print one complete json.

**Comment by JalexChen** [comment]
hey @alexkli  - this should be addressed in #24

**Comment by alexkli** [comment]
@JalexChen thanks, works!
