### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by vibin** [CircleCI-Public/CircleCI-Env-Inspector#21]
Hi, I'm receiving a permission denied error with below output:

```
$ docker run -it --rm cci-env-inspector

? Enter your CircleCI API token [hidden]
? Select a VCS GitHub
? Enter your GitHub API token [hidden]
? Select an account [hidden]
? Is this an Organization (Not a User)? Yes
Failed to get project variables with the following error:
 [ { message: 'Permission denied' } ]
```

For CircleCI API token - i've created a personal API token which has read + write scope.
For Github token - i've created a **classic** Personal access token which has `repo` and `workflow` scope.

The script was able to list all the organisations correctly, but it errors immediately after that...

**Comment by KyleTryon** [comment]
Hello @vibin,
We have updated the script and it no longer requires a GitHub token. Would you mind trying the latest version?

**Comment by vibin** [comment]
Works as advertised now. Thanks!
