### ISSUE TITLE
Not outputting all projects in Circle CI

### ISSUE THREAD

**Issue by mrtimp** [CircleCI-Public/CircleCI-Env-Inspector#23]
Hi there,

I ran this earlier and noticed that it is not including all projects (and their respective project level variables). I'm unable to determine why this is. I initially suspected it was because we disconnected from of the projects in Circle CI from GitHub as we are moving to GitHub Actions but haven't found a pattern to confirm this.  I'm not sure if the issue I'm facing is specific to the configuration of our account or if others may be facing the same issue without noticing.

Not sure if its related or not: https://github.com/CircleCI-Public/api-preview-docs/issues/97#issuecomment-1049449891

**Comment by jonseymour** [comment]
This maybe the same issue I reported in #22 although I do get the context info, but not the projects.

**Comment by mrtimp** [comment]
Its odd. I'm writing something in Go to use the `/api/v1.1/user/repos/github` API and then iterating to get the environment variables for each project as it doesn't seem that the /projects API returns ALL projects.

**Comment by KyleTryon** [comment]
Hello all, we just pushed an updated version of the app that has been _heavily_ refactored and no longer requires a GitHub API token. I believe this may resolve this issue. If you are able, please test the latest version and let us know if you are getting a more full result.

**Comment by mrtimp** [comment]
Hi @KyleTryon it does seem to be returning all projects and all associated GitHub accounts but now all of the variables as missing?

**Comment by KyleTryon** [comment]
@mrtimp sorry about that! Fixed.

**Comment by mrtimp** [comment]
Nice work @KyleTryon it looks like you've resolve the issue :-)

Thanks for quick turnaround.
