### ISSUE TITLE
Will this show the values?

### ISSUE THREAD

**Issue by milosivanovic** [CircleCI-Public/CircleCI-Env-Inspector#25]
CircleCI has famously never shown the value of secrets in the UI. Will this tool be able to show the values? In the README, it shows the value as "xxxx". Could the README be updated to explain if the value would be hidden or not?

**Comment by KyleTryon** [comment]
No, this tool nor any other tool will ever be able to tell you the values, these secrets are not exposed by any API. This tool is _nly_ for identifying where secrets live so that they may be replaced.

**Comment by milosivanovic** [comment]
Why add a value field then?

**Comment by KyleTryon** [comment]
We are returning as much information as the API will provide. The value field is how it is returned from the API
