### ISSUE TITLE
Is it possible to retrieve additional keys?

### ISSUE THREAD

**Issue by mauro-justgiving** [CircleCI-Public/CircleCI-Env-Inspector#45]
More of a question than an issue.
I can see the inspector is fetching the checkout SSH key(s?) through CircleCI's api call `/api/v2/project/{project-slug}/checkout-key`, but I can't see the Additional SSH Keys being fetched, or an API method for it.
Is it possible to return them? The question arises from the need of potentially rotate it!

Thanks

**Comment by JalexChen** [comment]
Unfortunately, this is explicitly left out of the API. You would not be able to retrieve these values at this time
