### ISSUE TITLE
Feature Request: "created_at" for project level environment variable

### ISSUE THREAD

**Issue by pbreault** [CircleCI-Public/CircleCI-Env-Inspector#50]
As the title says, it would be great to have the creation date for environment variables in projects. 
This is available for contexts already while projects only show the variable name and last characters.

**Comment by KyleTryon** [comment]
Hello,
  The CircleCI engineering teams are looking to add this functionality but it does not currently exist on the API. We will add date/time data for project environment variables as soon as they are available.
