### ISSUE TITLE
podman support

### ISSUE THREAD

**Issue by policyoftruth** [CircleCI-Public/CircleCI-Env-Inspector#57]
This isn't a big deal, but on some Enterprise Linux distributions, podman is supported over docker. I replaced 'docker' with 'podman' in the run.sh script and it works fine. A nice-to-have would be some form a basic distro or binary check. Thanks! ...or even a simple note in the README.md.

**Comment by KyleTryon** [comment]
On it 🫡 thank you!

**Comment by KyleTryon** [comment]
Solved in #61 for version 2. We hope to release it later today. Thanks!
