### ISSUE TITLE
Generic Help with script?

### ISSUE THREAD

**Issue by mathomp4** [CircleCI-Public/CircleCI-Env-Inspector#6]
This is just a "generic help" issue. I'm sort of a part-time admin and I'm happy if I can figure out how to get CircleCI things to work. So the whole "redo quite a lot of what you did over the last few years" is making me scared.

So, I read the threads and I get this script and I download it. And then it asks for a CircleCI API Token which I think I know how to make. Then it wants a GitHub API Token. I mean, I know how to generate a personal token, but what permissions do I need to give it? GitHub has like 50 options!

Are there more complete instructions than just "Follow the prompts?"

**Comment by EricRibeiro** [comment]
Hi Matthew 👋,

You can follow [this](https://circleci.com/docs/managing-api-tokens/#creating-a-personal-api-token) to create a personal CircleCI Token and [this](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic) to create a GitHub Personal Access Token. You want to give the `repo` scope for the latter:

![image](https://user-images.githubusercontent.com/21243061/210924394-3e77cc8c-c100-4a09-a8cc-e8bd1ae4888b.png)

I'll leave the issue open to remind us to update the `README`. Sorry for the inconvenience!

**Comment by KyleTryon** [comment]
Hello all,

We have updated the tool to where a GitHub token is no longer needed/used. Please give the latest version a try and let us know if you run into any issues.
